Token
codefellows/api-integration-server pull request #1
Opened 2021-12-06 19:17 UTC by KasonBraley

2021-12-06 19:23 UTC, JacobKnaack commented on __tests__/token.test.js
> +      .send(req)
set headers with .set for supertest, use .send to attach a requiest body

2021-12-06 20:15 UTC, KasonBraley commented on __tests__/token.test.js
> +      .send(req)
Removed this test implementation in https://github.com/codefellows/api-integration-server/pull/1/commits/7ee8d8e0ca012e2653ba443cb79d0764de84b7af.

2021-12-06 20:47 UTC, JacobKnaack requested changes

2021-12-06 20:47 UTC, JacobKnaack commented on __tests__/token.test.js
> +const express = require('express');
We can remove express and just mock the request / response / next parameters so that we don't have to integrate this test with things that will be handled by other modules.

2021-12-06 20:47 UTC, JacobKnaack commented on lib/router/auth.js
> +router.route('/api/*', bearer);
This will potentially cause an error when express tries to handle API routes not caught by other route handlers.   Since `bearer` is not a route handler, the request will hang (no response is sent in bearer except on error).   Let the test assert that bearer calls the appropriate Express functions.

2021-12-06 21:55 UTC, JacobKnaack requested changes
Update the test and router, on CI approval we will merge :)

2021-12-07 04:41 UTC, KasonBraley commented on lib/router/auth.js
> +router.route('/api/*', bearer);
Removed in https://github.com/codefellows/api-integration-server/pull/1/commits/ab67e82009d47bf2fa5ccc1b612173e2d3d3a9be

2021-12-07 04:41 UTC, KasonBraley commented on __tests__/token.test.js
> +const express = require('express');
Removed in https://github.com/codefellows/api-integration-server/pull/1/commits/acd074be85dd4a750a1692fd972a7c7b4676630a

2021-12-12 19:27 UTC, closed without merging