adds auth routes, user models, server file, dependencies, and test file
codefellows/api-integration-server pull request #2
Opened 2021-12-06 19:18 UTC by cburk2019

2021-12-06 21:42 UTC, JacobKnaack requested changes
Please pull and update with requested changes!

2021-12-07 02:08 UTC, cburk2019 commented on __tests__/authrouter.test.js
> +    const res = await server.get('/api').set('Authorization', 'Bearer ' + token);
Looks like we were able to get this up and going, thank you for your guidance!

2021-12-07 02:08 UTC, cburk2019 commented on __tests__/authrouter.test.js
> +    const res2 = await server.post('/api/v2/food')
Thank you for guiding me to the promised land!

2021-12-07 02:09 UTC, JacobKnaack approved these changes
Looks good!

2021-12-07 02:09 UTC, merged